### PR TITLE
Fix 307 too large status code

### LINKED ISSUE #60: When image too large, a 200 is returned, instead of a redirect code
So you end up on an empty page, instead of the image closest by.

```
curl -v https://customerimages.magnet.me/dev-ec08acf013a6048e4f4302532b4ce5e0_2000_896_2x.jpg?fit=crop
*   Trying 149.210.175.129...
* Connected to customerimages.magnet.me (149.210.175.129) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: *.magnet.me
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
* Server certificate: AddTrust External CA Root
> GET /dev-ec08acf013a6048e4f4302532b4ce5e0_2000_896_2x.jpg?fit=crop HTTP/1.1
> Host: customerimages.magnet.me
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.8.1
< Date: Wed, 03 Feb 2016 13:36:45 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: accept, content-type
< Access-Control-Allow-Method: GET
< Location: /dev-ec08acf013a6048e4f4302532b4ce5e0_3000_1792.jpg?fit=crop
< X-Redirect-Info: The requested image size falls outside of the allowed boundaries of this service. We are directing you to the closest available match.
<
* Connection #0 to host customerimages.magnet.me left intact
```

p.s. chapeau for the `X-Redirect-Info`, which  allowed us to see the error immediately

### PR DESCRIPTION
**Pull request by rogierslag**
Closes #60

### CODE REVIEW

**Comment by alexnederlof** [comment]
I can see your thesis is going well

**Comment by alexnederlof** [comment]
But :+1: for shipping speed

**Comment by rogierslag** [comment]
Damned it was stupid to overlook. I've released it as 1.0.1, as soon as docker hub is done you can reference it in your puppet file

@alexnederlof might want to tag arie as well here ;)

**Comment by TiddoLangerak** [comment]
Your fast

**Comment by alexnederlof** [comment]
@avandeursen When's @rogierslag graduation date again?

**Pull request merged**
